/*******************************************************************************
ENTERPRISE CUSTOMER SEGMENTATION & OPERATIONAL ANALYTICS CASE STUDY
Author: Mkulu-Statix
Database: Sakila DVD Rental (PostgreSQL)

Description:
This script forms the core data engineering and analytics layer for the business
intelligence portfolio project. It handles advanced data transformations, multi-table 
joins, feature engineering, and analytical window functions to extract strategic 
insights regarding inventory performance, customer loyalty, and revenue leakage.
*******************************************************************************/

-- PILLAR 1: INVENTORY OPTIMIZATION & FEATURE ENGINEERING PIPELINE

-- Objective: Classify the movie catalog into duration tiers and aggregate 
-- total revenue metrics to identify highly profitable cinematic segments.

SELECT 
    f.title,
    f.rating,
    f.length,
-- Feature Engineering: Creating categorical duration tiers (Dummy Variables)
    CASE 
        WHEN f.length <= 60 THEN 'Short Film'
        WHEN f.length > 60 AND f.length <= 120 THEN 'Medium Film'
        ELSE 'Long Movie'
    END AS film_duration_category,
-- Aggregating total revenue generated by this specific film
    SUM(p.amount) AS total_revenue_generated,
-- Statistical Metric: Count of how many times it was rented
    COUNT(r.rental_id) AS total_rental_count
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN payment p ON r.rental_id = p.rental_id
GROUP BY f.film_id, f.title, f.rating, f.length
ORDER BY total_revenue_generated DESC;



-- PILLAR 2: CUSTOMER LOYALTY & BEHAVIORAL SEQUENCE PIPELINE
-- Objective: Map customer purchase behaviors chronologically without collapsing 
-- transaction details, paving the way for customer lifetime value (CLV) analysis.

SELECT 
    p.customer_id,
    c.first_name,
    c.last_name,
    p.payment_date,
    p.amount,
    -- Analytical Window Function: Determining chronological transaction order per customer
    ROW_NUMBER() OVER(
        PARTITION BY p.customer_id 
        ORDER BY p.payment_date ASC
    ) AS payment_sequence_number,
-- Statistical Metric: Running average spend per transaction for this specific customer
    AVG(p.amount) OVER(
        PARTITION BY p.customer_id
    ) AS customer_historical_average_spend
FROM payment p
JOIN customer c ON p.customer_id = c.customer_id
ORDER BY p.customer_id, payment_sequence_number;



-- PILLAR 3: HIGH-VALUE VIP CUSTOMER SEGMENTATION
-- Objective: Isolate high-value customer cohorts using Common Table Expressions 
-- (CTEs) to find profiles that spend above the baseline customer cohort average.

WITH customer_spend_summary AS (
    SELECT 
        p.customer_id,
        c.first_name,
        c.last_name,
        c.email,
        SUM(p.amount) AS total_customer_lifetime_spend
    FROM payment p
    JOIN customer c ON p.customer_id = c.customer_id
    GROUP BY p.customer_id, c.first_name, c.last_name, c.email
)
SELECT 
    customer_id,
    first_name,
    last_name,
    email,
    total_customer_lifetime_spend
FROM customer_spend_summary
WHERE total_customer_lifetime_spend > (
    SELECT AVG(total_customer_lifetime_spend) 
    FROM customer_spend_summary
)
ORDER BY total_customer_lifetime_spend DESC;



-- PILLAR 4: REVENUE LEAKAGE & UNRETURNED INVENTORY TRACKING
-- Objective: Identify active revenue risk by filtering for unreturned assets 
-- (missing return dates) and mapping them back to customer contact details.

SELECT 
    r.rental_id,
    r.rental_date,
    f.title AS unreturned_movie_title,
    c.first_name,
    c.last_name,
    c.email,
-- Handling Missing Data: Confirming the asset has not been brought back
    r.return_date
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
JOIN customer c ON r.customer_id = c.customer_id
WHERE r.return_date IS NULL
ORDER BY r.rental_date ASC;